config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'

   resources :users do
  	get :watchlist
    get :offers
    resources :followers
    resources :followed_users
  end

  resources :inquiries do
    resources :messages
  end

	resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  get 'tags/:tag', to: 'listings#show', as: :tag

  resources :users do
    resources :feedbacks, shallow: true
  end

  resources :listings do
    resources :offers
  	post :watch
  	delete :unwatch
  end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end

  # Errors
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#error_500'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#not_found'
  end

  # get "*any", via: :all, to: "errors#not_found"

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  #Associations
  belongs_to :user
  belongs_to :category, inverse_of: :listings
  has_many :photos, dependent: :destroy 
  has_many :watches
  has_many :watchers, -> { uniq }, :through => :watches
  has_many :offers, dependent: :destroy
  has_many :feedbacks
  belongs_to :location, :dependent => :destroy
 
  # Nested Attributes
  accepts_nested_attributes_for :category, :photos
  
  # Tags
  acts_as_taggable_on :tags

  # Association validations
  validates_presence_of :category
  validates_presence_of :user
  # validates_presence_of :photo, message: "Please add a photo. Every listing minimum 1 photo."

  # Attribute validations
  validates_presence_of :title, message: "Please add a title."
  validates_presence_of :subtitle, message: "Please add a subtitle."
  validates_presence_of :price, message: "Please add a price."
  validates_presence_of :condition, message: "Please select a condition."

  scope :featured, -> { where(featured: true) }
  scope :active, -> { where(status: "active") }
  scope :hidden, -> { where(status: "hidden") }  
  scope :completed, -> { where(status: "completed") }
  scope :with_no_photos, -> { where("listings.id NOT IN (?)", Photo.where("photos.listing_id IS NOT NULL").select("DISTINCT photos.listing_id")) }
  
  #Status/State Machine
  state_machine :status, :initial => :active do
    state :active, :hidden, :completed

    event :hide do
      transition :active => :hidden
    end

    event :mark_complete do
      transition :active => :completed
    end
  end

  #Search
  def self.search(search)
    where("title ILIKE ?", "%#{search}%") 
  end

  #Other methods
  def build_offer(params, user)
    self.offers.new(price: params["price"], listing_id: params["listing_id"], user_id: user.id)
  end

  def ready_for_feedback?
    self.complete?
  end

  def complete?
    true if self.status == "complete"
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update]

  def index
    @listings = Listing.paginate(page: params[:page])
    if params[:search]
      @listings = Listing.search(params[:search]).order("created_at DESC")
    else
      @listings = Listing.all.order('created_at DESC')
    end
  end

  def new
    @listing = Listing.new
    @listing.build_category
    @listing.photos.build
  end

  def create
    @user = current_user
    @listing = @user.listings.build(listing_params)
    if @listing.save
      flash[:notices] = ['Listing created successfully']
      redirect_to listings_path
    else
      render 'new'
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @user = @listing.user
  end

  def edit
    @user = current_user
    @listing = @user.listings.find(params[:id])
    authorize! :read, @listing
  end

  def update
    @user = current_user
    @listing = @user.listings.find(params[:id])
    if @listing.update(listing_params)
      flash[:notices] = ["Your listing was successfully updated"]
      render 'show'
    else
      flash[:notices] = ["Your listing could not be updated"]
      render 'edit'
    end
  end

  def destroy
    @user = current_user
    @listing = @user.listings.find(params[:id])
    if @listing.destroy
      flash[:notices] = ['Your listing was successfully deleted']
      redirect_to '/listings'
    else
      flash[:alerts] = ['Sorry something went wrong. Your listing was not deleted.']
      redirect_to '/edit'
    end
  end

  def watch
    @listing = Listing.find(params[:listing_id])
    if @listing.watchers.exclude?(current_user)
      # current_user.watched_listings << @listing
      @listing.watchers << current_user
      flash[:notices] = ['Listing was successfully added to your watchlist']
      redirect_to @listing
    else
      flash[:notices] = ['This listing is already in your watchlist']
      redirect_to @listing
    end
  end

  def unwatch
    @listing = Listing.find(params[:listing_id])
    # if current_user.watched_listings.find(@listing).destroy && @listing.watches.find(current_user)
    if @listing.watchers.delete(current_user) 
      flash[:notices] = ['Listing successfully removed from your watch list']
      redirect_to user_watchlist_path(current_user)
    else
      flash[:notices] = ['This listing was not deleted from your watchlist']
      redirect_to user_watchlist_path(current_user)
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :subtitle, :description,
                                    :price, :condition, :brand, 
                                    :model, :case_type, :location, :tag_list,
                                    category_attributes: [:id, :category_id, :name], 
                                    photos_attributes: [:id, :image, :listing_id])
  end

  def tagged
    if params[:tag].present? 
      @listings = Listing.tagged_with(params[:tag])
    else 
      @listings = Listing.listingall
    end  
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/listings/edit.html.erb
<section class="wrapper">

<%= simple_form_for @listing, defaults: { input_html: { class: 'form-control' } } do |f| %>
  <%= f.input :title, input_html: { placeholder: 'Title', class: 'special' } %>
  <%= f.input :subtitle, input_html: { placeholder: 'Subtitle', maxlength: 20 } %>
  <%= f.input :description, input_html: { placeholder: 'Description' } %>
  <%= f.button :submit, input_html: { value: "Create Listing" } %>
<% end %>

</section>

app/views/listings/index.html.erb
<section class="wrapper">

	<section class="sub-nav">
		<section class="sub-nav-left">
			<%= form_tag(listings_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search, params[:search], placeholder: "Search Listings" %>
				<%= submit_tag "Search" %>
			<% end %>
		</section>

		<section class="sub-nav-right">
		Sub nav right
		</section>
	</section>	

	<section class="listings">

	<% if @listings.any? %>
		<% @listings.active.each do |listing| %>
		<section class="listing-snapshot">
		
		<section class="listing-snapshot-left">
			<section class="time-ago">Listed <%= time_ago_in_words(listing.created_at) %> ago
			</section>

			<section class="title">
				<%= link_to "#{listing.title}", listing_path(listing), class: "title" %>
			</section>
	
			
			<section class="attributes">
				<span>Listed by: <%= listing.user.email %></span>
				<span>Price: <%= listing.price %></span>
			</section>
		</section>	

			<section class="listing-snapshot-right">
				<% listing.photos.each do |photo| %>
					<%= image_tag photo.image.url(:medium) %>
				<% end %>
				<span class="location">Location: <%= listing.location %></span>
			</section>
		</section>
		<% end %>
	</ul>

	<% else %>
		<p>No listings yet</p>
	<% end %>

	</section>

	<aside class="listings-right">
		<h4>Hello from the right</h4>
	</aside>

</section>

app/views/listings/new.html.erb
<section class="wrapper">

<%= simple_form_for @listing, defaults: { input_html: { class: 'form-control' } } do |f| %>
  <%= f.fields_for :category do |c| %>
    <%= c.select :name, Category.all.map{|c| "#{c.name}" }, { :prompt => "Select category"}, class: "form-control" %>
  <% end %>
  <%= f.input :title, input_html: { placeholder: 'Title', class: 'special' } %>
  <%= f.input :subtitle, input_html: { placeholder: 'Subtitle', maxlength: 20 } %>
  <%= f.input :description, input_html: { placeholder: 'Description' } %>
	<%= f.input :price, input_html: { placeholder: 'Price' } %>
	<%= f.input :condition, input_html: { placeholder: 'Description' } %>
	<%= f.input :brand, input_html: { placeholder: 'Description' } %>
	<%= f.input :model, input_html: { placeholder: 'Description' } %>
	<%= f.label :case_type %>
	<%= f.select :case_type, ["Original HardCase", "HardCase", "GigBag", "No Case"], { placeholder: 'Description' } %>
	<%#= f.input :location, input_html: { placeholder: 'Description' } %>

		<%= f.fields_for :photos, html: {multipart: true} do |p| %>
			<%= p.file_field :image %>
		<% end %>

	<%= f.label :tag_list, "Tags (separated by commas)" %>
	<%= f.text_field :tag_list %>

  <%= f.button :submit, input_html: { value: "Create Listing" } %>
<% end %>

</section>

app/views/listings/show.html.erb
<section class="wrapper">

<% if @listing.user == current_user %>
	<%= link_to "Edit #{@listing.title}", edit_listing_path %>
	<%= link_to "Delete #{@listing.title}", listing_path(@listing), method: :delete %>
	<%= link_to "View All Offers on this listing", listing_offers_path(listing_id: @listing.id) %>
<% end %>

<% if @listing.user != current_user %>
	<%= link_to "Add to my watchlist - #{@listing.title}", listing_watch_path(@listing), method: :post %>
<% end %>

<% if @listing.tags.any? %>
<ul>
	Tags:
	<% @listing.tags.each do |tag| %>
	<li>
  	<%= tag.name %>
	</li>
	<% end %>
</ul>
<% end %>

<ul>
<li>Listing Title: <%= @listing.title %></li>
<li>Category: <%= @listing.category.name %></li>
<li>Subtitle: <%= @listing.try(:subtitle) %></li>
<li>Description: <%= @listing.try(:description) %></li>
</ul>

<% @listing.photos.each do |photo| %>
	<%= image_tag photo.image.url(:thumb) %>
<% end %>



<li>Listed by <%= @listing.user.email %></li>
<%= link_to "View Seller's Profile", user_path(@listing.user.id) %>

<%= link_to "Contact the Seller", inquiries_path(sender_id: current_user.id, recipient_id: @user.id, listing_id: @listing.id), method: 'post' %>

<%= link_to "Make an Offer", new_listing_offer_path(user_id: current_user.id, listing_id: @listing.id) %>

<%= link_to 'Leave feedback for this user', new_user_feedback_path(@user, @feedback, listing_id: @listing.id, seller_id: @listing.user.id, user_id: @user.id) %>


<%#= form_for [@listing, @offer], :url => listing_offer_path(@listing), method: :post do |f| %>
    <%#= f.label :price %>
    <%#= f.text_field :price, class: "form-control" %>
    <%#= f.submit "Submit Offer", class: "btn btn-primary" %>
 <%# end %>


</section>