config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'

   resources :users do
  	get :watchlist
    get :offers
    resources :followers
    resources :followed_users
  end

  resources :inquiries do
    resources :messages
  end

	resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  get 'tags/:tag', to: 'listings#show', as: :tag

  resources :users do
    resources :feedbacks, shallow: true
  end

  resources :listings do
    resources :offers
  	post :watch
  	delete :unwatch
  end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end

  # Errors
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#error_500'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#not_found'
  end

  # get "*any", via: :all, to: "errors#not_found"

end

app/models/user.rb
class User < ActiveRecord::Base

  ALLOWED_ROLES = %w(standard admin)

  has_many :listings, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_many :watched_listings,  -> { uniq }, :through => :watches, dependent: :destroy
  has_many :inquiries
  has_many :messages
  has_many :offers, dependent: :destroy
  belongs_to :location, :dependent => :destroy

  has_many :follower_relationships
  has_many :followers, :through => :follower_relationships, :foreign_key => "user_id"
  has_many :inverse_follower_relationships, :class_name => "FollowerRelationship", :foreign_key => "follower_id"
  has_many :followed_users, :through => :inverse_follower_relationships, :source => "user"

  #New proposed solution to Feedback relationship
  # has_many :authored_feedbacks, :class_name => "Feedback", :foreign_key => "author_id", :dependent => :destroy
  # has_many :received_feedbacks, -> { order("id DESC")}, :class_name => "Feedback", :foreign_key => "recipient_id", :dependent => :destroy
  # has_many :received_positive_feedbacks, -> { where(rating: true).order("id DESC") }, :class_name => "Feedback", :foreign_key => "recipient_id"
  # has_many :received_negative_feedbacks, -> { where(rating: false).order("id DESC") }, :class_name => "Feedback", :foreign_key => "recipient_id"

  # Feedbacks given - these associations to be removed.
  has_many :given_feedbacks_as_seller,
    -> { where(direction: 'seller_to_buyer') },
    class_name: 'Feedback',
    foreign_key: :seller_id
  has_many :given_feedbacks_as_buyer,
      -> { where(direction: 'buyer_to_seller') },
    class_name: 'Feedback',
    foreign_key: :buyer_id

  # Feedbacks receieved
  has_many :received_feedbacks_as_seller,
    -> { where(direction: 'seller_to_buyer') },
    class_name: 'Feedback',
    foreign_key: :seller_id
  has_many :received_feedbacks_as_buyer,
    -> { where(direction: 'buyer_to_seller') },
    class_name: 'Feedback',
    foreign_key: :buyer_id

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 9.megabytes
  
  validates_inclusion_of :role, in: ALLOWED_ROLES, allow_blank: false
  # validates_format_of :user_name, :with => /\A[A-Z0-9_]*\z/i
  # validates_length_of :user_name, :within => 3..20, :allow_nil => false, :allow_blank => false

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  def self.search(search)
    where("email ILIKE ?", "%#{search}%") 
  end

  def all_feedbacks
    Feedback.for_user(self)
  end

  def received_negative_feedbacks
    Feedback.negative.for_user(self)
  end

  def received_positive_feedbacks
    Feedback.positive.for_user(self)
  end
  

  def follows?(user)
    followed_users_by_id.include?(user.id)
  end

  def followed_people_by_id
    @followed_users_by_id ||= followed_users.group_by(&:id)
  end

  # after_create :send_welcome_mail
  
  # def send_welcome_mail
  #   UserMailer.sign_up_email(self).deliver
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notices] = ["Your profile was successfully updated"]
      render 'show'
    else
      flash[:notices] = ["Your profile could not be updated"]
      render 'edit'
    end
  end

  def watchlist
    @watched_listings = current_user.watched_listings.all
  end

  def offers
    @offers = current_user.offers.all
  end

  private

  def user_params
    params.require(:user).permit(:house_number, :street_address, :city, :postal_code, :country, :avatar, :role, :first_name, :last_name, :user_name)
  end

end

app/views/users/edit.html.erb
<section class="wrapper">

<% if URI(request.referer || '').path == '/users/sign_up' %>
	<h4>You are now signed up - please complete some profile information about yourself.</h4>
<% else %>
	<h4>Edit your profile and update</h4>
<% end %>

	<%= form_for @user, :url => user_path, html: {multipart: true} do |f| %>
	  <%= f.text_field :house_number, placeholder: "House Number/Name" %>
	  <%= f.text_field :street_address, placeholder: "Street" %>
	  <%= f.text_field :city, placeholder: "City" %>
	  <%= f.text_field :postal_code, placeholder: "Postal Code" %>
		<%= country_select("user", "country", { priority_countries: ["GB", "FR"], selected: @user.country }, { class: 'form-control', data: { attribute: "value" } }) %>
	  <%= f.file_field :avatar %>
	  <%= f.button :submit %>
	<% end %>

</section>

app/views/users/index.html.erb
<section class="wrapper">

<%= form_tag(users_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
	<%= submit_tag "Search" %>
<% end %>

<ul>
		<% if @users.any? %>
			<% @users.each do |user| %>
				<li.block>
					<%= link_to "#{user.email}", user_path(user) %>
				</li.block>
			<% end %>
		<% else %>
			<p>No users yet</p>
		<% end %>
</ul>

</section>

app/views/users/offers.html.erb
<section class="wrapper">
<ul>
	<% if @offers.any? %>
		<% @offers.each do |offer| %>
			<li><%= offer.listing.title %> -->> <%= offer.price %> </li>
			<%= link_to "View Offer Details", listing_offer_path(offer.listing, offer) %>
			<%= link_to "Delete Offer", listing_offer_path(offer.listing, offer), method: :delete  %>
		<% end %>
	<% else %>
		<li>You have made no offers</li>
	<% end %>
</ul>

</section>

app/views/users/show.html.erb
<section class="wrapper">
	<ul>
		<li><%= @user.email %></li>
	<ul>
</section>


<section class="wrapper">

	Profile for <%= @user.email %>
	<%= @user.city %>
	<%= @user.country %>
	<%= image_tag @user.avatar.url(:thumb) %>

	<% if current_user == @user %>
		<%= link_to "Edit Profile", edit_user_path %>
		<%= link_to "Your offers", user_offers_path(current_user) %>
	<% end %>

	<p><%= link_to "View #{@user.email}'s Feedback", user_feedbacks_path(@user) %></p>
	<p><%= link_to "Follow #{@user.email}", new_user_followed_user_path(@user) %></p>	
</section>

app/views/users/watchlist.html.erb
<section class="wrapper">
<ul>
	<% if @watched_listings.any? %>
		<% @watched_listings.each do |listing| %>
			<li><%= link_to listing.title, listing_path(listing) %> <%= link_to "Remove from watchlist - #{listing.title}", listing_unwatch_path(listing), method: :delete %></li>
		<% end %>
	<% else %>
		<li>No items in your watchlist yet :(</li>
	<% end %>
</ul>

</section>