config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'

   resources :users do
  	get :watchlist
    get :offers
    resources :followers
    resources :followed_users
  end

  resources :inquiries do
    resources :messages
  end

	resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end

  get 'tags/:tag', to: 'listings#show', as: :tag

  resources :users do
    resources :feedbacks, shallow: true
  end

  resources :listings do
    resources :offers
  	post :watch
  	delete :unwatch
  end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end

  # Errors
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#error_500'

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'errors#not_found'
  end

  # get "*any", via: :all, to: "errors#not_found"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMarketplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div style="background:white;">
<%= debug(params) if Rails.env.development? %>
</div>
<section class="wrapper">
	<section class="nav">
		<h1 class="title">GuitarTrader</h1>
		<ul>
			<% if user_signed_in? %>
			  <li><%= link_to "My Profile", user_path(current_user) %></li>
			  <li><%= link_to "My Watch List", user_watchlist_path(current_user) %></li>
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to 'Your Messages', inquiries_path %></li>
			  <li><%= link_to "All Listings", listings_path %></li>
        <li><%= link_to "Add a listing", new_listing_path %></li>
			  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <li>Signed in as <%= current_user.email %></li>
			<% else %>
			  <li><%= link_to "Sign in", new_user_session_path %></li>
			  <li><%= link_to "Sign up", new_user_registration_path %></li>
			  <li><%= link_to "All Listings", listings_path %></li>
			<% end %>
		</ul>
	</section>

	<section class="flash">

	<% if flash && flash[:alerts] %>
  <div class="container">
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% flash[:alerts].each do |error| %>
        <%= error %>
      </div>
    <%end%>
  </div>
<%end%>

<% if flash && flash[:notices] %>
  <div class="container">
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% flash[:notices].each do |error| %>
        <%= error %>
      </div>
    <%end%>
  </div>
<%end%>

</section>

</section>

	<%= yield %>

  <section class="wrapper">
    <footer>
      <%= link_to "About Us", about_page_path %>
      <%= link_to "Contact Us", contact_page_path %>
      <%= link_to "FAQ", faq_page_path %>
    </footer>
  </section>

</body>
</html>